#!/usr/bin/env node

import { mkdir, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { Prisma } from "@prisma/client"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const backendRoot = resolve(__dirname, "..")
const projectRoot = resolve(backendRoot, "..")

const BACKEND_OUTPUT_PATH = resolve(backendRoot, "src/types/generated.ts")
const FRONTEND_OUTPUT_PATH = resolve(
  projectRoot,
  "frontend/src/types/generated.ts"
)

const HEADER_COMMENT = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated from:
 * - Backend Prisma schema (database models)
 * - Backend business logic types
 * 
 * To regenerate, run: npm run types:generate
 * 
 * Generated: ${new Date().toISOString()}
 */`

const SECTION_TITLES = {
  databaseModels:
    "// ==================== Database Models (from Prisma) ====================",
  businessLogic:
    "// ==================== Business Logic Types ====================",
  apiResponse:
    "// ==================== API Response Types ====================",
  votingErrors:
    "// ==================== Voting Error Types ====================",
  typeGuards: "// ==================== Type Guards ====================",
  requestResponse:
    "// ==================== Request/Response Shapes ====================",
}

const PRISMA_SCALAR_MAP = {
  String: "string",
  Int: "number",
  BigInt: "bigint",
  Float: "number",
  Decimal: "number",
  Boolean: "boolean",
  DateTime: "Date",
  Json: "unknown",
  Bytes: "Uint8Array",
}

function mapScalar(field) {
  const baseType = PRISMA_SCALAR_MAP[field.type] ?? "unknown"
  const typeWithArray = field.isList ? `${baseType}[]` : baseType
  return field.isRequired ? typeWithArray : `${typeWithArray} | null`
}

function buildModelInterfaces(models) {
  return models
    .map(model => {
      const scalarFields = model.fields.filter(field => field.kind === "scalar")

      const fieldLines = scalarFields.map(field => {
        const tsType = mapScalar(field)
        const optionalToken = field.isRequired ? "" : "?"
        return `  ${field.name}${optionalToken}: ${tsType}`
      })

      const docBlock = [
        "/**",
        ` * ${model.name} model from database`,
        " */",
      ].join("\n")
      const interfaceBlock = [
        docBlock,
        `export interface ${model.name} {`,
        ...fieldLines,
        "}",
      ].join("\n")

      return interfaceBlock
    })
    .join("\n\n")
}

const BUSINESS_LOGIC_BLOCK = `${SECTION_TITLES.businessLogic}

/**
 * Idea with user vote status
 * Добавляет флаг hasVoted к базовой сущности Idea
 */
export interface IdeaWithVoteStatus extends Idea {
  hasVoted: boolean
}`

const API_RESPONSE_BLOCK = `${SECTION_TITLES.apiResponse}

/**
 * Generic API Response wrapper
 */
export interface ApiResponse<T> {
  data: T
  success: boolean
}

/**
 * API Error structure
 */
export interface ApiError {
  message: string
  statusCode: number
  error?: string
}`

const VOTING_ERRORS_BLOCK = `${SECTION_TITLES.votingErrors}

/**
 * Voting error types enum
 */
export enum VotingErrorType {
  DUPLICATE_VOTE = "DUPLICATE_VOTE",
  VOTE_LIMIT_EXCEEDED = "VOTE_LIMIT_EXCEEDED",
  IDEA_NOT_FOUND = "IDEA_NOT_FOUND",
}

/**
 * Extended voting error with type discriminator
 */
export interface VotingError extends ApiError {
  type: VotingErrorType
}`

const TYPE_GUARDS_BLOCK = `${SECTION_TITLES.typeGuards}

/**
 * Type guard to check if error is a VotingError
 */
export function isVotingError(error: unknown): error is VotingError {
  return (
    typeof error === "object" &&
    error !== null &&
    "type" in error &&
    "message" in error &&
    "statusCode" in error &&
    Object.values(VotingErrorType).includes((error as VotingError).type)
  )
}

/**
 * Type guard to check if error is an ApiError
 */
export function isApiError(error: unknown): error is ApiError {
  return (
    typeof error === "object" &&
    error !== null &&
    "message" in error &&
    "statusCode" in error
  )
}`

const REQUEST_RESPONSE_BLOCK = `${SECTION_TITLES.requestResponse}

/**
 * Vote success response
 */
export interface VoteResponse extends ApiResponse<IdeaWithVoteStatus> {}

/**
 * Ideas list response
 */
export interface IdeasListResponse extends ApiResponse<IdeaWithVoteStatus[]> {}

/**
 * Single idea response
 */
export interface IdeaResponse extends ApiResponse<IdeaWithVoteStatus> {}`

function buildFile(models) {
  const modelInterfaces = buildModelInterfaces(models)

  return [
    HEADER_COMMENT,
    "",
    SECTION_TITLES.databaseModels,
    "",
    modelInterfaces,
    "",
    BUSINESS_LOGIC_BLOCK,
    "",
    API_RESPONSE_BLOCK,
    "",
    VOTING_ERRORS_BLOCK,
    "",
    TYPE_GUARDS_BLOCK,
    "",
    REQUEST_RESPONSE_BLOCK,
    "",
  ]
    .filter(Boolean)
    .join("\n")
}

async function ensureDirForFile(filePath) {
  const directory = dirname(filePath)
  await mkdir(directory, { recursive: true })
}

async function writeGeneratedFile(filePath, content) {
  await ensureDirForFile(filePath)
  await writeFile(filePath, `${content}\n`, "utf8")
}

async function main() {
  const models = Prisma.dmmf?.datamodel?.models ?? []

  if (models.length === 0) {
    throw new Error(
      "No Prisma models found. Run `npm run prisma:generate` first."
    )
  }

  const fileContent = buildFile(models)

  await Promise.all([
    writeGeneratedFile(BACKEND_OUTPUT_PATH, fileContent),
    writeGeneratedFile(FRONTEND_OUTPUT_PATH, fileContent),
  ])

  console.log("✅ Generated types for backend and frontend")
}

main().catch(error => {
  console.error("❌ Failed to generate types:")
  console.error(error)
  process.exitCode = 1
})
