#!/usr/bin/env node

/**
 * Скрипт для билда shared types пакета
 *
 * Этот скрипт:
 * 1. Билдит @logiclike/types пакет
 * 2. Копирует сгенерированные типы во frontend
 */

import { execSync } from "child_process"
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "fs"
import { dirname, join } from "path"
import { fileURLToPath } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))

// Пути
const projectRoot = join(__dirname, "../../")
const typesPackagePath = join(projectRoot, "packages/types")
const frontendTypesPath = join(projectRoot, "frontend/src/types")
const sourceFile = join(typesPackagePath, "dist/index.d.ts")
const targetFile = join(frontendTypesPath, "generated.ts")

console.log("📦 Building shared types package...")
console.log(`   Project root: ${projectRoot}`)
console.log(`   Types package: ${typesPackagePath}`)
console.log(`   Frontend types: ${frontendTypesPath}`)

try {
  // 1. Билдим types пакет
  console.log("\n   Building @logiclike/types...")
  execSync("npm run build", {
    cwd: typesPackagePath,
    stdio: "inherit",
  })

  console.log(`\n   Source file: ${sourceFile}`)
  console.log(`   Target file: ${targetFile}`)

  // 2. Создаем директорию для типов во frontend
  mkdirSync(frontendTypesPath, { recursive: true })

  // 3. Читаем содержимое .d.ts файла
  console.log("\n   Reading source file...")
  let content = readFileSync(sourceFile, "utf-8")
  console.log(`   Content length: ${content.length} bytes`)

  // 4. Добавляем заголовок
  const header = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated from shared types package.
 * To regenerate, run: npm run types:generate
 * 
 * Source: packages/types/src/index.ts
 * Generated: ${new Date().toISOString()}
 */

`

  // 5. Записываем файл с заголовком
  writeFileSync(targetFile, header + content, "utf-8")

  console.log("✅ Types generated successfully!")
  console.log(`   Source: ${sourceFile}`)
  console.log(`   Target: ${targetFile}`)
} catch (error) {
  console.error("❌ Error generating types:", error.message)
  process.exit(1)
}
}

// Создаём директорию если её нет
mkdirSync(dirname(outputPath), { recursive: true })

// Записываем файл
writeFileSync(outputPath, generatedTypes, "utf-8")

console.log("✅ Types generated successfully!")
console.log(`📁 Output: ${outputPath}`)
