// Domain Entity Types (generated by Prisma)
export type { Idea, Vote } from '@prisma/client';

// DTOs (Data Transfer Objects)
export interface IdeaWithVoteStatus {
  id: number;
  title: string;
  description: string;
  votesCount: number;
  createdAt: Date;
  hasVoted: boolean;
}

export interface VoteResult {
  success: boolean;
  idea: {
    id: number;
    votesCount: number;
    hasVoted: boolean;
  };
}

// Error Types
export enum VotingErrorType {
  VOTE_LIMIT_EXCEEDED = 'VOTE_LIMIT_EXCEEDED',
  ALREADY_VOTED = 'ALREADY_VOTED',
  IDEA_NOT_FOUND = 'IDEA_NOT_FOUND',
}

export class VotingError extends Error {
  constructor(
    public type: VotingErrorType,
    message: string,
  ) {
    super(message);
    this.name = 'VotingError';
  }
}
